spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
springdoc:
  swagger-ui.url: /event-manager-openapi.yaml